- name: Gather Facts and then pull most recent config
  hosts: bigip

  tasks:
      - name: Get all of the facts from my BIG-IP
        bigip_facts:
            server: "{{ inventory_hostname }}"
            user: "{{ hostvars[inventory_hostname].user }}"
            password: "{{ hostvars[inventory_hostname].password }}"
            include: device_group
            validate_certs: "false"
        delegate_to: localhost

      - name: determine sync-failover device group
        set_fact:
          sync_failover_dg: "{{ item }}"
        when: device_group[item]['type'] == "DGT_FAILOVER"
        with_items: "{{ device_group.keys() }}"
        delegate_to: localhost

      - name: Pull Config From Group
        bigip_configsync_action:
            server: "{{ inventory_hostname }}"
            sync_most_recent_to_device: yes
            device_group: "{{ sync_failover_dg.split('/')[2] }}"
            user: "{{ hostvars[inventory_hostname].user }}"
            password: "{{ hostvars[inventory_hostname].password }}"
            validate_certs: "false"
        delegate_to: localhost
