- name: Create BIG-IP UCS File and Upload it to server; then delete on BIG-IP
  hosts: bigipve
  connection: local

  tasks:
      - debug: var=ansible_date_time

      - debug: msg="the current date is {{ ansible_date_time.date }}"
      - name: Get all of the facts from my BIG-IP
        bigip_facts:
            user: "admin"
            password: "admin"
            include: "system_info"
