- name: Test bigip_facts
  hosts: bigip
  connection: local
 
  tasks:
      - name: Get all of the facts from my BIG-IP
        bigip_facts:
            server: "{{ inventory_hostname }}"
            user: "admin"
            password: "admin"
            include: system_info,device,software,provision,key
            validate_certs: "false"
      - debug: msg="the hostname is {{ system_info.system_information.host_name }}"
