- name: Create LTM Pool, Add 2 Members and then create 2 LTM Virtuals (80/443) that reference pool
  hosts: bigip

  tasks:
      - name: Create Pool example-pool
        bigip_pool:
            name: example-pool
            partition: Common
            lb_method: round-robin
            monitors:
              - tcp_half_open
            server: "{{ inventory_hostname }}"
            user: "{{ hostvars[inventory_hostname].user }}"
            password: "{{ hostvars[inventory_hostname].password }}"
            state: present
            validate_certs: "false"
        delegate_to: localhost

      - name: Add Members to Pool
        bigip_pool_member:
            pool: example-pool
            partition: Common
            host: "{{ hostvars[inventory_hostname].prefix }}.{{ item.addr }}"
            port: 80
            server: "{{ inventory_hostname }}"
            user: "{{ hostvars[inventory_hostname].user }}"
            password: "{{ hostvars[inventory_hostname].password }}"
            state: present
            validate_certs: "false"
        with_items:
          - addr: "2.1"
          - addr: "2.2"
        delegate_to: localhost
