---

- name: Create a VIP, pool, pool members, and nodes
  hosts: bigip10200


  tasks:
    - name: Create a pool
      bigip_pool:
          server: "{{ ansible_host }}"
          lb_method: ratio-member
          name: web
          slow_ramp_time: 120
          user: "{{ bigip_username }}"
          password: "{{ bigip_password }}"
          validate_certs: False
      delegate_to: localhost


    - name: Create node1
      bigip_node:
          server: "{{ ansible_host }}"
          host: 10.10.10.10
          name: node-1
          password: "{{ bigip_password }}"
          user: "{{ bigip_username }}"
          validate_certs: False
      delegate_to: localhost
