- name: Set NTP Server to pool.ntp.org
  hosts: bigip

  tasks:
      - name: Set NTP Server to pool.ntp.org
        bigip_device_ntp:
            server: "{{ inventory_hostname }}"
            ntp_servers:
              - pool.ntp.org
            user: "{{ hostvars[inventory_hostname].user }}"
            password: "{{ hostvars[inventory_hostname].password }}"
            validate_certs: "false"
        delegate_to: localhost
